version: "2"
run:
  concurrency: 3
linters:
  default: none
  enable:
    - asciicheck
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nestif
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
